root = "."
tmp_dir = "tmp"

[build]
  delay = 500

  cmd = "go build -o ./tmp/main ./cmd/hermes/main.go"
  bin = "./tmp/main"

  exclude_dir = ["assets", "tmp", "vendor", "public", "testdata"]

  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test.go"]

  kill_delay = "500ms"
  send_interrupt = true
  stop_on_error = true

[log]
  time = true
  main_only = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
